### ISSUE TITLE
401 Unauthorised error.

### ISSUE THREAD

**Issue by WinnerWind** [GSGBen/t2md#50]
Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoldenSyrupGames.T2MD.Cli.RunAsync(CliOptions options)
   at GoldenSyrupGames.T2MD.Cli.Main(String[] args)
   at GoldenSyrupGames.T2MD.Cli.<Main>(String[] args)

Not sure what is causing this. I have done everything as the README said, and after trying without that long URL, the program hangs. How to fix?

**Comment by WinnerWind** [comment]
Update : Removed the URL from the KEY from the JSON file after creating a new power up called "Trello to Markdown" (as the URL had). Program recognises every board, does some processing but output folder is always empty.

**Comment by WinnerWind** [comment]
Update AGAIN!

**For those of you struggling, remember two things**
If you give the output folder as just a name, like \trellobackup\ instead of a file directory, the program automatically makes the folder in the root directory (C:\\trellobackup\ for this example)

**How I fixed it**
Make a power up and name it verbatim " Trello To Markdown " (other names failed in my experience). Then, removing the URL from the key, only keep the key given in the API page and the token from the token page, then try.

Docs really need an update.

**Comment by zenminimalist** [comment]
@WinnerWind Can you explain how you got it to run? I'm struggling to understand how you did. 
E.g. What do you mean when you say "Removed the URL from the KEY from the JSON" and what URL do I put in the powerup?
