### ISSUE TITLE
Unhandled exception. System.Exception: ./2024-09-20/t2md/xxxxx.json missing required properties.

### ISSUE THREAD

**Issue by jimcmcdonald** [GSGBen/t2md#58]
Starting seeing the following exception this week, it appears to be occurring on all boards - thanks for taking a look 

```Unhandled exception. System.Exception: ./2024-09-20/t2md/xxxx.json missing required properties.
   at GoldenSyrupGames.T2MD.Cli.ProcessTrelloBoardAsync(TrelloApiBoardModel trelloApiBoard, CliOptions options, Dictionary`2 duplicateBoardSuffixes)
   at GoldenSyrupGames.T2MD.Cli.RunAsync(CliOptions options)
   at GoldenSyrupGames.T2MD.Cli.Main(String[] args)
   at GoldenSyrupGames.T2MD.Cli.<Main>(String[] args)```

$ ./t2md --version
t2md 4.1.1

**Comment by GSGBen** [comment]
Hmmm, I'm not seeing the same. From your title it looks like you have a folder per day. Can you diff a working and broken .json of the same board and let me know which properties are missing please?

**Comment by jimcmcdonald** [comment]
First, *thank you* for taking a look at this and for publishing the tool. In running it today, to get the diff you requested, I'm finding it is now working.  Perhaps there was a transient error on Trello's end.  I run my t2md based process every Friday  and last Friday was the first and only time I've seen the error.

**Comment by jimcmcdonald** [comment]
I did not see the issue again today, so I'll close the issue as resolved.  Thank you.
